-- MyFamilyFinance — initial schema
-- Generated by hand from plan: obsidian-witty-panda.md
-- Idempotent where possible.

set search_path = public;

-- ====================================================================
-- 1. budget_accounts — fixed budget categories per user
-- ====================================================================
create table if not exists budget_accounts (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users(id) on delete cascade,
  name         text not null,
  icon         text,
  color        text,
  sort_order   int not null default 0,
  is_archived  boolean not null default false,
  created_at   timestamptz not null default now(),
  constraint budget_accounts_user_name_unique unique (user_id, name)
);
create index if not exists budget_accounts_user_idx on budget_accounts (user_id);

-- ====================================================================
-- 2. bank_accounts — real Thai bank account references
-- ====================================================================
create table if not exists bank_accounts (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null references auth.users(id) on delete cascade,
  bank_code       text not null,
  account_number  text not null,
  nickname        text not null,
  created_at      timestamptz not null default now()
);
create index if not exists bank_accounts_user_idx on bank_accounts (user_id);

-- ====================================================================
-- 3. budget_account_banks — M:N link
-- ====================================================================
create table if not exists budget_account_banks (
  budget_account_id uuid not null references budget_accounts(id) on delete cascade,
  bank_account_id   uuid not null references bank_accounts(id) on delete cascade,
  primary key (budget_account_id, bank_account_id)
);

-- ====================================================================
-- 4. monthly_periods — month anchor
-- ====================================================================
create table if not exists monthly_periods (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users(id) on delete cascade,
  period_month  date not null,
  note          text,
  closed_at     timestamptz,
  created_at    timestamptz not null default now(),
  constraint monthly_periods_user_month_unique unique (user_id, period_month),
  constraint monthly_periods_first_of_month_chk check (extract(day from period_month) = 1)
);
create index if not exists monthly_periods_user_month_idx on monthly_periods (user_id, period_month desc);

-- ====================================================================
-- 5. incomes — multiple incomes per period allowed
-- ====================================================================
create table if not exists incomes (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references auth.users(id) on delete cascade,
  period_id      uuid not null references monthly_periods(id) on delete cascade,
  amount         numeric(14,2) not null check (amount > 0),
  received_date  date not null,
  source         text,
  note           text,
  created_at     timestamptz not null default now()
);
create index if not exists incomes_period_idx on incomes (period_id);
create index if not exists incomes_user_date_idx on incomes (user_id, received_date desc);

-- ====================================================================
-- 6. monthly_allocations — allocation per budget account per period
-- ====================================================================
create table if not exists monthly_allocations (
  id                 uuid primary key default gen_random_uuid(),
  period_id          uuid not null references monthly_periods(id) on delete cascade,
  budget_account_id  uuid not null references budget_accounts(id) on delete restrict,
  amount             numeric(14,2) not null check (amount >= 0),
  constraint monthly_allocations_period_account_unique unique (period_id, budget_account_id)
);
create index if not exists monthly_allocations_period_idx on monthly_allocations (period_id);

-- ====================================================================
-- 7. expenses — expense records
-- ====================================================================
create table if not exists expenses (
  id                 uuid primary key default gen_random_uuid(),
  user_id            uuid not null references auth.users(id) on delete cascade,
  period_id          uuid not null references monthly_periods(id) on delete cascade,
  budget_account_id  uuid not null references budget_accounts(id) on delete restrict,
  amount             numeric(14,2) not null check (amount > 0),
  expense_date       date not null,
  note               text,
  created_at         timestamptz not null default now()
);
create index if not exists expenses_period_account_idx on expenses (period_id, budget_account_id);
create index if not exists expenses_user_date_idx on expenses (user_id, expense_date desc);

-- ====================================================================
-- RLS — owner-only access on every table
-- ====================================================================
alter table budget_accounts       enable row level security;
alter table bank_accounts         enable row level security;
alter table budget_account_banks  enable row level security;
alter table monthly_periods       enable row level security;
alter table incomes               enable row level security;
alter table monthly_allocations   enable row level security;
alter table expenses              enable row level security;

drop policy if exists "owner_all" on budget_accounts;
create policy "owner_all" on budget_accounts
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "owner_all" on bank_accounts;
create policy "owner_all" on bank_accounts
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "owner_all" on monthly_periods;
create policy "owner_all" on monthly_periods
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "owner_all" on incomes;
create policy "owner_all" on incomes
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "owner_all" on expenses;
create policy "owner_all" on expenses
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- monthly_allocations: derive owner via period_id → monthly_periods.user_id
drop policy if exists "owner_all" on monthly_allocations;
create policy "owner_all" on monthly_allocations
  for all
  using (
    exists (
      select 1 from monthly_periods p
      where p.id = monthly_allocations.period_id and p.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from monthly_periods p
      where p.id = monthly_allocations.period_id and p.user_id = auth.uid()
    )
  );

-- budget_account_banks: both sides must belong to the user
drop policy if exists "owner_all" on budget_account_banks;
create policy "owner_all" on budget_account_banks
  for all
  using (
    exists (select 1 from budget_accounts ba where ba.id = budget_account_id and ba.user_id = auth.uid())
    and exists (select 1 from bank_accounts ba2 where ba2.id = bank_account_id and ba2.user_id = auth.uid())
  )
  with check (
    exists (select 1 from budget_accounts ba where ba.id = budget_account_id and ba.user_id = auth.uid())
    and exists (select 1 from bank_accounts ba2 where ba2.id = bank_account_id and ba2.user_id = auth.uid())
  );
